set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER "clang-19")
set(CMAKE_CXX_COMPILER "clang++-19")
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

set(CMAKE_C_STANDARD 23) # 90, 99, 11, 17, 23
set(CMAKE_C_STANDARD_REQUIRED TRUE)
set(CMAKE_CXX_STANDARD 26)  # 98, 11, 14, 17, 20, 23, 26
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_FLAGS_INIT "-target x86_64-w64-mingw32")
set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++ -target x86_64-w64-mingw32")
set(CMAKE_CXX_STANDARD_LIBRARIES "-lc++ -lc++abi")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-target x86_64-w64-mingw32")
